"Resource/UI/HudAmmoWeapons.res"
{
	"AmmoInClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClip"
		"font"			"QOFHealthAmmoHandel"
		"fgcolor"		"White"
		"xpos"			"cs-0.5"
		"ypos"			"r106"
		"zpos"			"5"
		"wide"			"140"
		"tall"			"42"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
		
	}		
	"AmmoInClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInClipShadow"
		"font"			"QOFHealthAmmoHandel"
		"fgcolor"		"Black"
		"xpos"			"-1"
		"ypos"			"-1"
		"zpos"			"4"  
		"wide"			"140"
		"tall"			"42"
		"visible"		"0"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%Ammo%"

		"pin_to_sibling" "AmmoInClip"
	}

	"AmmoInReserve"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserve"
		"font"			"QOFHealthAmmoHandel"
		"fgcolor"		"White"
		"xpos"			"cs+0.3"
		"ypos"			"r106"
		"ypos_lodef"	"10"
		"zpos"			"7"
		"wide"			"140"
		"tall"			"42"
		"tall_lodef"	"30"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"		
		"labelText"		"%AmmoInReserve%"
	}		
	"AmmoInReserveShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoInReserveShadow"
		"font"			"QOFHealthAmmoHandel"
		"fgcolor"		"Black"
		"xpos"			"1"
		"ypos"			"-1"
		"zpos"			"6"  
		"wide"			"140"
		"tall"			"42"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%AmmoInReserve%"
		"pin_to_sibling" "AmmoInReserve"
		"pin_corner_to_sibling" "PIN_TOPRIGHT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"
	}
							
	"AmmoNoClip"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClip"
		"font"			"QOFHealthAmmoHandel"
		"fgcolor"		"White"
		"xpos"			"cs+0.3"
		"ypos"			"r106"
		"zpos"			"5"
		"wide"			"140"
		"tall"			"42"
		"tall_lodef"	"45"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"	
		"labelText"		"%Ammo%"
	}
	"AmmoNoClipShadow"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"AmmoNoClipShadow"
		"font"			"QOFHealthAmmoHandel"
		"fgcolor"		"Black"
		"xpos"			"1"
		"ypos"			"-1"
		"zpos"			"4"
		"wide"			"140"
		"tall"			"42"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"center"
		"labelText"		"%Ammo%"
		"pin_to_sibling" "AmmoNoClip"
		"pin_corner_to_sibling" "PIN_TOPRIGHT"
		"pin_to_sibling_corner" "PIN_TOPRIGHT"
	}
    "HudWeaponAmmoBG"   // dead
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"HudWeaponAmmoBG"
		"xpos"			"9999"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"90"
		"tall"			"45"
		"visible"		"1"
		"enabled"		"1"
		"image"			"../hud/ammo_blue_bg"
		"scaleImage"	"1"		
		"teambg_2"		"../hud/ammo_red_bg"
		"teambg_2_lodef"	"../hud/ammo_red_bg_lodef"
		"teambg_3"		"../hud/ammo_blue_bg"
		"teambg_3_lodef"	"../hud/ammo_blue_bg_lodef"
		"teambg_4"		"../hud/ammo_custom_bg"
		"teambg_4_lodef"	"../hud/ammo_custom_bg"
	}		
}
